### ISSUE TITLE
Unable to use IP spoof

### ISSUE THREAD

**Issue by DuckRui** [HalilDeniz/Dosinator#10]
Hello, this is really an excellent job
I encountered an issue while using this code for testing. I am unable to use the function of IP spoofing. 
Specifically, when using this code on my server a without using spoofing IP, a large number of syn requests can be observed on the target machine b. 
But once I activate the IP spoofing function, the target machine B cannot receive syn requests. 
May I ask what the possible reason is? Could it be that my server vendor performed IP address verification, causing my syn request to be intercepted?

**Comment by HalilDeniz** [comment]
Hello, first of all, thank you for your feedback:
IP spoofing usually fails because ISPs or hosting providers block packets with spoofed IP addresses. Network security devices can detect and block spoofed IP packets. The target machine may have security measures in place to reject incoming spoofed IP packets. Finally, misconfigured packets may be discarded throughout the network or blocked before reaching the destination.
and if you want, you can join our discord group and reach more: https://discord.gg/productionbrain

**Comment by DuckRui** [comment]
> Hello, first of all, thank you for your feedback: IP spoofing usually fails because ISPs or hosting providers block packets with spoofed IP addresses. Network security devices can detect and block spoofed IP packets. The target machine may have security measures in place to reject incoming spoofed IP packets. Finally, misconfigured packets may be discarded throughout the network or blocked before reaching the destination. and if you want, you can join our discord group and reach more: https://discord.gg/productionbrain

So is there any good way to perform IP spoofing? Perhaps there are ISPs that do not prevent IP spoofing of packets ?
By the way, I clicked on this link, but it ultimately showed that I couldn't be invited
